# Generated by Django 3.0.5 on 2020-07-27 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedtables', to=settings.AUTH_USER_MODEL),
        ),
    ]
