# Generated by Django 3.0.5 on 2020-08-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20200730_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='propic',
            field=models.CharField(default='defaultpropic.png', max_length=200),
        ),
    ]
