# Generated by Django 3.0.5 on 2020-08-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0007_auto_20200816_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='banner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='table',
            name='pp_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
