# Generated by Django 3.0.5 on 2020-08-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post', to='lunch.Comment'),
        ),
    ]
